version: '3.8'

x-service: &service
  environment:
    - SPRING_PROFILES_ACTIVE=dev

services:

  app:
    build:
      context: ./frontend/app
    ports:
      - "8085:80"

  keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: auth-db
        DB_SCHEMA: keycloak
        DB_USER: postgres
        DB_PASSWORD: postgres
      volumes:
      - ./keycloak-config/realm-export.json:/opt/keycloak/data/import/realm.json
      depends_on:
        - auth-db
      ports:
        - "8080:8080"
      networks:
        - net-auth
      command:
      - start-dev
      - --import-realm

  bank-service:
    build: ./backend/bank-service
    ports:
      - '8083:8083'
    networks:
      - net-bankdb
      - net-gateway
      - net-auth

  auth-service:
    <<: *service
    build: ./backend/auth-service
    ports:
      - '8082:8082'
    networks:
      - net-auth
      - net-gateway

  api-gateway:
    <<: *service
    build: ./backend/gateway-service
    ports:
      - '8081:8081'
    networks:
      - net-gateway

  auth-db:
    container_name: auth-db
    image: postgres:14.7
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - auth-db:/var/lib/postgresql/data
    networks:
      - net-auth
      

  bankdb:
    container_name: bank_db
    image: postgres:14.7
    restart: unless-stopped
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    ports:
      - '5433:5432'
    volumes:
      - bankdb:/var/lib/postgresql/data
    networks:
      - net-bankdb

  

volumes:
  auth-db:
    driver: local
  bankdb:
    driver: local

networks:
  net-gateway:
  net-bankdb:
  net-auth:
