version: '3.8'

x-service: &service
  environment:
    - SPRING_PROFILES_ACTIVE=dev

services:
  bank-service:
    build: bank-service
    ports:
      - '8083:8083'
    networks:
      - net-apiGw-bankServ

  auth-service:
    <<: *service
    build: auth-service
    ports:
      - '8082:8082'
    networks:
      - net-apiGw-authServ

  api-gateway:
    <<: *service
    build: gateway-service
    ports:
      - '8081:8081'
    networks:
      - net-apiGw-bankServ
      - net-apiGw-authServ


networks:
  net-apiGw-bankServ:
  net-apiGw-authServ:
