server:
  port: 8082

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    org.springframework.security: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: SafeBankAppGateway
            client-secret: 4WtyLPeWhfLNkHGsTarf7peROsqQMnLG
            authorization-grant-type: authorization_code
            redirect-uri: ${keycloak-client.server-url}/login/oauth2/code/keycloak
            scope: openid
        provider:
          keycloak:
            authorization-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/auth
            token-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/token
            user-info-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
            user-name-attribute: name
            user-info-authentication-method: header
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/SafeBankApp
keycloak-client:
  server-url: http://localhost:8080
  realm: SafeBankApp


keycloak:
  master-realm: master
  client-id: SafeBankAppGateway
  client-secret: 4WtyLPeWhfLNkHGsTarf7peROsqQMnLG
  scope: openid
  authorization-grant-type: password
  user-info-uri: http://localhost:8080/realms/SafeBankApp/protocol/openid-connect/userinfo
  token-uri: http://localhost:8080/realms/SafeBankApp/protocol/openid-connect/token
  jwk-set-uri: http://localhost:8080/realms/SafeBankApp/protocol/openid-connect/certs
  server-url: http://localhost:8080/
  realm: SafeBankApp
  admin: admin
  admin-password: admin