server:
  port: 8081
  ssl:
    enabled: true
    key-store: classpath:gateway.jks
    key-store-password: gateway
    key-alias: gateway
    key-store-type: JKS
    key-store-provider: SUN
    trust-store: classpath:gateway.jks
    trust-store-password: gateway
    trust-store-type: JKS

logging:
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR

spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          trusted-x509-certificates:
            - "classpath:auth-service.pem"
            - "classpath:bank-service.pem"

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "https://localhost:8443"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - OPTIONS

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: admin-cli
            client-secret: 0G1ce0uHFDEJRcVD3qG4pDlj3YF8ZDTW
            authorization-grant-type: authorization_code
            redirect-uri: ${keycloak-client.server-url}/login/oauth2/code/keycloak
            scope: openid
        provider:
          keycloak:
            authorization-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/auth
            token-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/token
            user-info-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
            user-name-attribute: name
            user-info-authentication-method: header
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
          issuer-uri: http://keycloak:8080/realms/SafeBankApp
keycloak-client:
  server-url: http://keycloak:8080
  realm: SafeBankApp