server:
  port: 8083

keycloak-client:
  server-url: http://keycloak:8080
  realm: SafeBankApp

secrets:
  encryption-key: "7d3480a02ebe5b24d46dc14c1805677d5f9615b6f57e48a39d7e8f8e6f4cc1a3"

spring:

  mvc:
    log-request-details: true

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect

  sql:
    init:
      platform: h2
      mode: never