server:
  port: 8083

keycloak-client:
  server-url: http://keycloak:8080
  realm: SafeBankApp

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

spring:

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
          issuer-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}

  mvc:
    log-request-details: true # for debugging

  datasource:
    url: jdbc:postgresql://bank_db:5432/bankdb
    username: sa
    password: sa

  sql:
    init:
      platform: postgres
      mode: always
      separator: "^^^ END OF SCRIPT ^^^"



  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true