server:
  port: 8083

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

spring:

  mvc:
    log-request-details: true # for debugging

  datasource:
    url: jdbc:postgresql://bank_db:5432/bankdb
    username: sa
    password: sa

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect