services:
 keycloak:
   image: jboss/keycloak
   environment:
     - KEYCLOAK_USER=admin
     - KEYCLOAK_PASSWORD=admin
     - KEYCLOAK_IMPORT=/tmp/realm-export.json
   ports:
     - "8080:8080"
   volumes:
     - ./keycloak-config:/tmp
